### ISSUE TITLE
Make the HDF5 loader portable 

### ISSUE THREAD

**Issue by jdhayhurst** [eQTL-Catalogue/eQTL-SumStats#32]
dockerise the loader and make the tsv --> hdf5 generation run in a portable pipeline e.g. Nextflow

**Comment by jdhayhurst** [comment]
nf pipeline
tsv --> hdf5
plan:
```
- args:
 - meta
  - file: <name>
   - id: <identifier>
   - study: <study>
   - qtl_group: <qtl>
   - quant method: <quant>
   - tissue: <tissue>
   - etc...
 - study_out_dir
 - chrom_out_dir

- processes:
 - study load
  - input:
   - file
   - study
   - qtl group
   - tissue ont
   - quant method
   - chromosome
  - output
   - study hdf5 file per chrom

 - index hdf5 files
  - input:
   - study hdf5
  - output:
   - study hdf5 (indexed)

 - consolidate all study hdf5 (including those already done) by chrom ( after study load is complete)
 # use .collect() for previous and then iterate over all files in study_out_dir/$chrom
  - input:
   - chrom
   - quant method
   - study hdf5s (all files in study_out_dir)
   - study level meta
    - study
    - qtl group
    - tissue ont
  - output:
   - chrom hdf5

 - index chrom hdf5
  - input:
   - chrom hdf5
  - output:
   - chrom hdf5 (indexed)
```
